version: '3.4'

# SSL CERTIFICATE and forcing so that the gateway is secure 
services:
  ocelot-api-gateway:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTPS_PORT=443
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${CertPass}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/app/certs/smitenoobleague_xyz.pfx
    volumes:
      - ./certs:/app/certs

  db:
    volumes:
        - mysql_data:/var/lib/mysql

volumes:
  mysql_data: